principleXpath = '//*[@id="principal"]'
rateOfIntrestXpath = '//*[@id="interest"]'
timePeriod1Xpath = '//*[@id="tenure"]'
timePeriod2Xpath = '//*[@id="tenurePeriod"]'
frequencyXpath = '//*[@id="frequency"]'
calculateButtonXpath = '//*[@id="fdMatVal"]/div[2]/a[1]/img'
clearButtonXpath = '//*[@id="fdMatVal"]/div[2]/a[2]/img'
maturityValueXpath = '//span[@id="resp_matval"]/strong'

dismissNotificationPopupXpath = '//*[@id="wzrk-cancel"]'
